-- Seed 12 real indie games for MVP launch
INSERT INTO public.games (title, description, hook_text, trailer_url, steam_url, itchio_url, dev_x_handle, tags, status, upvotes) VALUES
(
  'Hades II',
  'Battle beyond the Underworld using dark sorcery as you take on the Titan of Time in this bewitching sequel to the award-winning roguelike dungeon crawler.',
  'The gods have fallen. Time to rise.',
  'https://www.youtube.com/embed/cB514fm5omQ',
  'https://store.steampowered.com/app/1145350/Hades_II/',
  NULL,
  '@SupergiantGames',
  ARRAY['Roguelike', 'Action', 'Mythology', 'Indie'],
  'approved',
  145
),
(
  'Manor Lords',
  'Manor Lords is a medieval strategy game featuring in-depth city building, large-scale tactical battles, and complex economic and social simulations.',
  'Build your medieval empire, one manor at a time.',
  'https://www.youtube.com/embed/3j2pFKr6VJg',
  'https://store.steampowered.com/app/1363080/Manor_Lords/',
  NULL,
  '@LordsManor',
  ARRAY['Strategy', 'City Builder', 'Medieval', 'Simulation'],
  'approved',
  231
),
(
  'Balatro',
  'The poker roguelike. Balatro is a hypnotically satisfying deckbuilder where you play illegal poker hands, discover game-changing jokers, and trigger adrenaline-pumping synergies.',
  'Poker has never been this addictive.',
  'https://www.youtube.com/embed/R24k1UCw_bk',
  'https://store.steampowered.com/app/2379780/Balatro/',
  NULL,
  '@LocalThunk',
  ARRAY['Roguelike', 'Deckbuilder', 'Card Game', 'Strategy'],
  'approved',
  412
),
(
  'Animal Well',
  'A game about exploring a surreal and hand-drawn world filled with weird creatures and hidden surprises.',
  'Every pixel hides a secret.',
  'https://www.youtube.com/embed/OIA_sIy-ioU',
  'https://store.steampowered.com/app/813230/Animal_Well/',
  NULL,
  '@bigmodegames',
  ARRAY['Metroidvania', 'Puzzle', 'Exploration', 'Pixel Art'],
  'approved',
  189
),
(
  'Palworld',
  'Fight, farm, build and work alongside mysterious creatures called "Pals" in this brand-new multiplayer, open-world survival and crafting game.',
  'Pokémon with guns. Need we say more?',
  'https://www.youtube.com/embed/y2KRXI98zes',
  'https://store.steampowered.com/app/1623730/Palworld/',
  NULL,
  '@Palworld_EN',
  ARRAY['Survival', 'Crafting', 'Open World', 'Multiplayer'],
  'approved',
  567
),
(
  'Lorelei and the Laser Eyes',
  'A puzzle-adventure set in a gothic noir mansion filled with mysteries, riddles, and a conspiracy spanning centuries.',
  'Your mind is the only weapon you need.',
  'https://www.youtube.com/embed/7YjFGWV8F3k',
  'https://store.steampowered.com/app/2008920/Lorelei_and_the_Laser_Eyes/',
  NULL,
  '@SimogoGames',
  ARRAY['Puzzle', 'Adventure', 'Mystery', 'Atmospheric'],
  'approved',
  94
),
(
  '1000xRESIST',
  '1000xRESIST is a thrilling sci-fi adventure about resilience, memory, and the power of sisterhood.',
  'One thousand memories. One resistance.',
  'https://www.youtube.com/embed/S0QLeR0aXfI',
  'https://store.steampowered.com/app/1675010/1000xRESIST/',
  NULL,
  '@sunsetvisitor',
  ARRAY['Adventure', 'Sci-Fi', 'Story Rich', 'Narrative'],
  'approved',
  76
),
(
  'UFO 50',
  'UFO 50 is a collection of 50 single and multiplayer games from the creators of Spelunky and Downwell.',
  '50 games. One legendary collection.',
  'https://www.youtube.com/embed/yMDG5nPjzoo',
  'https://store.steampowered.com/app/1147860/UFO_50/',
  NULL,
  '@mossmouth',
  ARRAY['Arcade', 'Retro', 'Collection', 'Multiplayer'],
  'approved',
  203
),
(
  'Neva',
  'Experience the moving tale of a young woman and her lifelong bond with a magnificent wolf as they embark on a thrilling adventure.',
  'A bond that transcends time.',
  'https://www.youtube.com/embed/BbEfXxh7gSA',
  'https://store.steampowered.com/app/2420660/Neva/',
  NULL,
  '@nomadastudiobcn',
  ARRAY['Adventure', 'Platformer', 'Emotional', 'Art'],
  'approved',
  127
),
(
  'Thank Goodness You''re Here!',
  'A slapstick time-loop adventure about a traveling salesman trapped in a bizarre British town.',
  'The most British game you''ll play this year.',
  'https://www.youtube.com/embed/Q67jwQr8PqM',
  'https://store.steampowered.com/app/2366980/Thank_Goodness_Youre_Here/',
  NULL,
  '@CoalSupper',
  ARRAY['Comedy', 'Adventure', 'Puzzle', 'Hand-drawn'],
  'approved',
  158
),
(
  'Arranger: A Role-Puzzling Adventure',
  'A puzzle adventure where every move shifts the world beneath your feet in a unique grid-based world.',
  'Slide into adventure.',
  'https://www.youtube.com/embed/KUOmI4vBJ6Y',
  'https://store.steampowered.com/app/2318620/Arranger_A_RolePuzzling_Adventure/',
  NULL,
  '@furnitureandmat',
  ARRAY['Puzzle', 'Adventure', 'Unique', 'Cozy'],
  'approved',
  89
),
(
  'Hollow Knight: Silksong',
  'Discover a vast, haunted kingdom in Silksong, the sequel to the award-winning action-adventure.',
  'Descend into a kingdom of silk and song.',
  'https://www.youtube.com/embed/pFAknD_9U7c',
  'https://store.steampowered.com/app/1030300/Hollow_Knight_Silksong/',
  NULL,
  '@TeamCherryGames',
  ARRAY['Metroidvania', 'Action', 'Platformer', 'Hand-drawn'],
  'approved',
  892
);